#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
nm-applet &
caffeine &
xfce4-power-manager &

if $(xrandr -q | grep -q "^DP-1 connected"); then
    $HOME/.screenlayout/external2.sh
    export MONITOR=HDMI-2
    bspc monitor HDMI-2 -d 1 2 3 4 5
elif $(xrandr -q | grep -q "^eDP-1 connected"); then
    export MONITOR=eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5
else
    export MONITOR=eDP1
    bspc monitor eDP1 -d 1 2 3 4 5
fi

$HOME/.config/polybar/launch.sh &
$HOME/.fehbg &

bspc config border_width            2
bspc config border_radius           0
bspc config window_gap              30
bspc config top_padding             15
bspc config focused_border_color    \#f4eeeb
bspc config normal_border_color     \#0f1419
bspc config split_ratio             0.5
bspc config click_to_focus          true

# monocle layout (leader + m)
bspc config borderless_monocle      true
bspc config gapless_monocle         false

# app-specific rules
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a Gpick state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Thunar state=floating
bspc rule -a Arandr state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Lxappearance state=pseudo_tiled
