#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
killall xfce4-panel &

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-2 -d 6

bspc config border_width            2
bspc config window_gap              60
bspc config top_padding             25
bspc config focused_border_color    \#f4eeeb
bspc config normal_border_color     \#171717
bspc config split_ratio             0.5
bspc config click_to_focus          true

# monocle layout (leader + m)
bspc config borderless_monocle      true
bspc config gapless_monocle         false

# app-specific rules
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a Gpick state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Spotify state=pseudo_tiled desktop='^6'
