#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              40
bspc config top_padding             25
bspc config focused_border_color    \#5c6370
bspc config normal_border_color     \#2f343f

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true

# always float xfce4-datetime-plugin window
bspc rule --add Wrapper-2.0 state=floating
bspc rule --add Gpick state=floating
bspc rule --add Timeshift-gtk state=floating
