#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              60
bspc config top_padding             25
bspc config focused_border_color    \#f4eeeb
bspc config normal_border_color     \#1c202c
bspc config split_ratio             0.5
bspc config click_to_focus          true

# monocle layout (leader + m)
bspc config borderless_monocle      true
bspc config gapless_monocle         false

# always float xfce4-datetime-plugin window
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a Gpick state=floating
bspc rule -a Timeshift-gtk state=floating

# plank dock on top
bspc rule -a Plank layer=above manage=on border=off
